schema_version = "1.0.0"

id = "mt2_tools"
version = "0.3.0"
name = "MT2 Tools"
tagline = "Import, edit and export MMORPG Tycoon 2 models"
maintainer = "Yamikhal"
type = "add-on"
tags = ["Import-Export", "Game Engine"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

[permissions]
files = "Read game models and write model files into your mod folder"
