from . import (
    animation,
    color_picker,
    convert,
    export,
    flat_shading,
    helpers,
    importing,
    materials,
    paint,
    palette,
    rig,
    select_color,
    swatches,
    theme,
    updates,
)

CLASSES = (
    *importing.CLASSES,
    *export.CLASSES,
    *paint.CLASSES,
    *flat_shading.CLASSES,
    *palette.CLASSES,
    *color_picker.CLASSES,
    *swatches.CLASSES,
    *select_color.CLASSES,
    *helpers.CLASSES,
    *materials.CLASSES,
    *animation.CLASSES,
    *rig.CLASSES,
    *theme.CLASSES,
    *convert.CLASSES,
    *updates.CLASSES,
)
